name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build Project
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t tanmaysinghx/ts-sso-service-1727:latest .

      - name: Publish image to Docker Hub
        run: docker push tanmaysinghx/ts-sso-service-1727:latest

deploy_to_docker_hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/ts-sso-service-1727:latest

      # Add steps to deploy to a local Docker server here
      - name: Deploy to Local Docker Server
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/ts-sso-service-1727:latest localhost:5000/ts-sso-service-1727:latest
          docker push localhost:5000/ts-sso-service-1727:latest
